project:
  type: website
  output-dir: docs

website:
  title: "~ jim"
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: ~ home
      - posts.qmd
    right:
      - icon: github
        href: https://github.com/jimgar
      - icon: stack-overflow
        href: https://stackoverflow.com/users/20624624/jimgar
      - icon: linkedin
        href: https://www.linkedin.com/in/jim-gardner-330368ab/
      - icon: mastodon
        href: https://fosstodon.org/@jimgar

format:
  html:
    code-link: true
    theme: [darkly, styles.scss]
    mainfont: Atkinson Hyperlegible
    toc: true