project:
  type: website
  output-dir: docs

website:
  title: "Jim Gardner"
  twitter-card: true
  navbar:
    right:
      - href: index.qmd
        text: Home
  page-footer:
    background: light
    left: 
      - text: "Website built with Quarto, R, and RStudio"
    right:
      - icon: github
        href: https://github.com/jimgar
      - icon: stack-overflow
        href: https://stackoverflow.com/users/20624624/jimgar
      - icon: linkedin
        href: https://www.linkedin.com/in/jim-gardner-330368ab/
      - icon: envelope-heart
        href: contact.qmd
    border: false

format:
  html:
    theme: 
      light: minty
      dark: superhero
    css: styles.css
    toc: true



