project:
  type: website
  output-dir: docs

website:
  title: "Jim Gardner"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/jimgar
      - icon: stack-overflow
        href: https://stackoverflow.com/users/20624624/jimgar
      - icon: linkedin
        href: https://www.linkedin.com/in/jim-gardner-330368ab/
      - icon: envelope-heart
        href: mailto:jimmahgee@gmail.com
  page-footer:
    center: 
      - icon: emoji-laughing
    border: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



