project:
  type: website
  output-dir: docs

website:
  title: "Jim Gardner"
  navbar:
    right:
      - href: index.qmd
        text: Home
  page-footer:
    center: 
      - text: "Website built with Quarto, R, and RStudio"
    border: false

format:
  html:
    theme: 
      light: minty
      dark: superhero
    css: styles.css
    toc: true



